# Generated by Django 4.0.6 on 2022-07-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sahifa', models.PositiveIntegerField()),
                ('yil', models.PositiveIntegerField()),
                ('janr', models.CharField(choices=[['Detektiv', 'Detektiv'], ['Drama', 'Drama'], ['Fantastika', 'Fantastika'], ['Ilmiy', 'Ilmiy'], ['Diniy', 'Diniy'], ['Tragediya', 'Tragediya']], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('st_raqam', models.IntegerField()),
                ('bitiruvchi', models.BooleanField()),
                ('kitoblar_soni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Yozuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tirik', models.BooleanField()),
                ('birth_year', models.PositiveIntegerField(default=0)),
                ('millat', models.CharField(choices=[["O'zbek", "O'zbek"], ['Turk', 'Turk'], ['Ingliz', 'Ingliz'], ['Arab', 'Arab'], ['Hind', 'Hind']], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('qaytardi', models.CharField(choices=[['Ha', 'Ha'], ["Yo'q", "Yo'q"]], max_length=5)),
                ('qaytarilgan_sana', models.DateField()),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kitob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='yozuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.yozuvchi'),
        ),
    ]
