# Generated by Django 4.0.6 on 2022-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='aaa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(default=True),
        ),
    ]
